SELECT table_name FROM user_tables WHERE table_name IN (
  'USERS','ROLES','USER_ROLES','TXN_STATE','TXN_STATE_HISTORY',
  'RISK_SCORING_RESULTS','TXN_IDEMPOTENCY','REVIEW_CASE_ACTIONS',
  'RECONCILIATION_RUNS','RECONCILIATION_ITEMS','DATALAKE_SNAPSHOTS',
  'ETL_LOGS','ANALYST_REPORTS','SUPPRESSION_RULES','CUSTOMERS',
  'MERCHANTS','CHANNELS','TRANSACTIONS_LIVE','REVIEW_CASES','LOANS',
  'MODEL_CONFIGS','AUDIT_LOGS','RULE_HITS','CARD_VELOCITY_STATS'
) ORDER BY 1;
EXIT;

SELECT * FROM USERS;