CREATE ROLE PROJECT_ADMIN;
GRANT CONNECT, RESOURCE TO PROJECT_ADMIN;
GRANT CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE TO PROJECT_ADMIN;
GRANT CREATE USER, DROP USER, ALTER USER TO PROJECT_ADMIN;
GRANT CONNECT, RESOURCE TO PROJECT_ADMIN WITH ADMIN OPTION;
GRANT GRANT ANY PRIVILEGE TO PROJECT_ADMIN;
GRANT CREATE ROLE TO PROJECT_ADMIN;
GRANT DROP ANY ROLE TO PROJECT_ADMIN;
GRANT GRANT ANY ROLE TO PROJECT_ADMIN;


CREATE USER ADMIN IDENTIFIED BY "123456";
GRANT PROJECT_ADMIN TO ADMIN;
ALTER USER ADMIN QUOTA UNLIMITED ON USERS;


