"""add_analyst_model_configs_suppression_rules

Revision ID: 2daa102b7ade
Revises: 39562f5b173b
Create Date: 2026-04-19 14:26:28.865995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import oracle

# revision identifiers, used by Alembic.
revision: str = '2daa102b7ade'
down_revision: Union[str, Sequence[str], None] = '39562f5b173b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_configs',
    sa.Column('config_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('param_name', sa.String(length=100), nullable=False),
    sa.Column('param_value', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('config_id'),
    sa.UniqueConstraint('model_name', 'param_name', name='uq_model_configs_name_param')
    )
    op.create_table('suppression_rules',
    sa.Column('rule_id', sa.String(length=36), nullable=False),
    sa.Column('rule_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.add_column('loans', sa.Column('person_age', sa.Integer(), nullable=True))
    op.add_column('loans', sa.Column('person_income', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('loans', sa.Column('person_home_ownership', sa.String(length=20), nullable=True))
    op.add_column('loans', sa.Column('person_emp_length', sa.Integer(), nullable=True))
    op.add_column('loans', sa.Column('loan_grade', sa.String(length=2), nullable=True))
    op.add_column('loans', sa.Column('loan_intent', sa.String(length=30), nullable=True))
    op.add_column('loans', sa.Column('cb_person_default_on_file', sa.String(length=1), nullable=True))
    op.add_column('loans', sa.Column('cb_person_cred_hist_length', sa.Integer(), nullable=True))
    op.drop_column('loans', 'credit_score')
    op.drop_column('loans', 'employment_years')
    op.drop_column('loans', 'debt_to_income_ratio')
    op.drop_column('loans', 'annual_income')
    op.drop_column('loans', 'prior_default_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('prior_default_count', sa.INTEGER(), nullable=True))
    op.add_column('loans', sa.Column('annual_income', oracle.NUMBER(precision=18, scale=2, asdecimal=True), nullable=True))
    op.add_column('loans', sa.Column('debt_to_income_ratio', oracle.NUMBER(precision=6, scale=4, asdecimal=True), nullable=True))
    op.add_column('loans', sa.Column('employment_years', oracle.NUMBER(precision=5, scale=2, asdecimal=True), nullable=True))
    op.add_column('loans', sa.Column('credit_score', sa.INTEGER(), nullable=True))
    op.drop_column('loans', 'cb_person_cred_hist_length')
    op.drop_column('loans', 'cb_person_default_on_file')
    op.drop_column('loans', 'loan_intent')
    op.drop_column('loans', 'loan_grade')
    op.drop_column('loans', 'person_emp_length')
    op.drop_column('loans', 'person_home_ownership')
    op.drop_column('loans', 'person_income')
    op.drop_column('loans', 'person_age')
    op.drop_table('suppression_rules')
    op.drop_table('model_configs')
    # ### end Alembic commands ###
