"""add_loan_approval_ai_columns

Revision ID: 39562f5b173b
Revises: 6949263b39c8
Create Date: 2026-04-17 09:51:15.620704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39562f5b173b'
down_revision: Union[str, Sequence[str], None] = '6949263b39c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('annual_income', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('loans', sa.Column('employment_years', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('loans', sa.Column('debt_to_income_ratio', sa.Numeric(precision=6, scale=4), nullable=True))
    op.add_column('loans', sa.Column('credit_score', sa.Integer(), nullable=True))
    op.add_column('loans', sa.Column('prior_default_count', sa.Integer(), nullable=True))
    op.add_column('loans', sa.Column('pd_score', sa.Numeric(precision=6, scale=4), nullable=True))
    op.add_column('loans', sa.Column('risk_level', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'risk_level')
    op.drop_column('loans', 'pd_score')
    op.drop_column('loans', 'prior_default_count')
    op.drop_column('loans', 'credit_score')
    op.drop_column('loans', 'debt_to_income_ratio')
    op.drop_column('loans', 'employment_years')
    op.drop_column('loans', 'annual_income')
    # ### end Alembic commands ###
